### ISSUE TITLE
The question about visibility in the master list

### ISSUE THREAD

**Issue by DarkBanan** [HMBSbige/A2SService#1]
Hi! Thanks for the good service. But there is a question. How can I add fakeserver to steam masterlist? I tried to replace the steam id (from the working server) - it did not work.

**Comment by HMBSbige** [comment]
This repository only implements the [Server queries](https://developer.valvesoftware.com/wiki/Server_queries), the [Master Server Query Protocol](https://developer.valvesoftware.com/wiki/Master_Server_Query_Protocol) is not considered.
